server:
  port: 8072
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
spring:
  cloud:
    gateway:
      discovery.locator:
        enabled: true
        lowerCaseServiceId: true
      routes:
        - id: auth
          uri: http://localhost:8100
          predicates:
            - Path=/auth/**
      default-filters:
        - TokenRelay=
        - RemoveRequestHeader=Cookie,Set-Cookie
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8100/auth/realms/woodpecker
        registration:
          quotes-client:
            provider: keycloak
            client-id: gateway
            client-secret: tGqqQx15CmTHLjyEGOA8jwVyuxI90p99
            scope:
              - email
              - profile
              - roles
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true