version: '3.1'
services:
  db_woodpecker:
    image: postgres:13
    container_name: "db_woodpecker"
    ports:
      - "5432:5432"
    networks:
      - woodpecker_network
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - ./database:/var/lib/postgresql
  woodpecker:
    image: sashaeremin/mywood:0.0.5
    container_name: "woodpecker_app"
    ports:
      - "8080:8080"
    networks:
      - woodpecker_network
    environment:
      - spring.datasource.url=jdbc:postgresql://db_woodpecker:5432/postgres
  redis-wd:
    image: redis
    container_name: "redis_wd"
    ports:
      - "6379:6379"
    networks:
      - woodpecker_network
networks:
  woodpecker_network:








