version: '3.1'
services:
  db_woodpecker:
    image: postgres:13
    container_name: "db_woodpecker"
    ports:
      - "5432:5432"
    networks:
      - woodpecker_network
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - ./database:/var/lib/postgresql
  woodpecker-backend:
    build: .
    image: sashaeremin/woodpecker_backend:0.0.1
    container_name: "woodpecker-backend"
    ports:
      - "9090:9090"
    networks:
      - woodpecker_network
    environment:
      - spring.datasource.url=jdbc:postgresql://db_woodpecker:5432/postgres
  woodpecker-client:
    build: /home/kali/IdeaProjects/woodClient
    image: sashaeremin/mywood_client:0.0.1
    container_name: "woodpecker-client"
    ports:
      - "80:80"
    networks:
      - woodpecker_network
#  redis-wd:
#    image: redis
#    container_name: "redis_wd"
#    ports:
#      - "6379:6379"
#    networks:
#      - woodpecker_network
networks:
  woodpecker_network:
    driver: bridge








