version: '3.1'
services:
  db-woodpecker:
    image: postgres:13
    container_name: "db-woodpecker"
    ports:
      - "5432:5432"
    networks:
      - woodpecker_network
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - ./database:/var/lib/postgresql
  keycloak:
    image: jboss/keycloak
    restart: always
    environment:
      DB_VENDOR: postgres
      DB_ADDR: db-woodpecker
      DB_PORT: 5432
      DB_DATABASE: keycloak
      DB_USER: user
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - "8100:8080"
    networks:
      - woodpecker_network
  config-server:
    build: /home/oem/IdeaProjects/configserver
    image: sashaeremin/config_server:0.0.1
    container_name: "config-server"
    ports:
      - "8071:8071"
    networks:
      - woodpecker_network
    environment:
      - spring.cloud.config.server.git.password=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
      - spring.cloud.config.server.git.username=sashaeremin08051998@gmail.com
    depends_on: [db-woodpecker]
  eureka-server:
    build: /home/oem/IdeaProjects/eureka
    image: sashaeremin/eureka_server:0.0.1
    container_name: "eureka-server"
    ports:
      - "8070:8070"
    networks:
      - woodpecker_network
    environment:
      - spring.profiles.active=prod
      - spring.cloud.config.uri=http://config-server:8071
    depends_on: [config-server]
  gateway:
    build: /home/oem/IdeaProjects/gateway
    image: sashaeremin/gateway:0.0.1
    container_name: "gateway"
    ports:
      - "8072:8072"
    networks:
      - woodpecker_network
    environment:
      - spring.profiles.active=prod
      - spring.cloud.config.uri=http://config-server:8071
    depends_on: [ config-server, eureka-server ]
  woodpecker-store:
    build: /home/oem/IdeaProjects/store
    image: sashaeremin/woodpecker_store:0.0.1
    container_name: "woodpecker-store"
    ports:
      - "9091:9091"
    networks:
      - woodpecker_network
    environment:
      - spring.profiles.active=prod
      - spring.cloud.config.uri=http://config-server:8071
    depends_on: [ eureka-server ]
  woodpecker-backend:
    build: .
    image: sashaeremin/woodpecker_backend:0.0.1
    container_name: "woodpecker-backend"
    ports:
      - "9090:9090"
    networks:
      - woodpecker_network
    environment:
      - spring.profiles.active=prod
      - spring.cloud.config.uri=http://config-server:8071
    depends_on: [ eureka-server ]
networks:
  woodpecker_network:
    driver: bridge








