#  https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
spring:
  security:
    ignored:
      - "*.bundle.*"
  profiles:
    default: prod
  #  sql:
#    init:
#      mode: always
  cache:
    cache-names: {"userByMail", "orders", "mapsByManager"}
    redis:
      time-to-live: 10M
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    show-sql: true
    open-in-view: false
    properties:
      #  http://docs.jboss.org/hibernate/orm/5.3/userguide/html_single/Hibernate_User_Guide.html#configurations
      hibernate:
        format_sql: true
        default_batch_fetch_size: 20
        # https://stackoverflow.com/questions/21257819/what-is-the-difference-between-hibernate-jdbc-fetch-size-and-hibernate-jdbc-batc
        jdbc.batch_size: 20
#        show_sql: true
#    hibernate:
#      ddl-auto: create
  #  datasource:
  #    url: jdbc:h2:mem:wood
  #    username: sa
  #    password:
  #    driverClassName: org.h2.Driver
  #  h2:
  #    console:
  #      path: /h2
  #      enabled: true

  # Jackson Serialization Issue Resolver
  jackson.visibility:
    field: any
    getter: none
    setter: none
    is-getter: none

  # https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html#common-application-properties-cache
  flyway:
    baseline-on-migrate: true
    locations: db/migration
    enabled: false
  redis:
    host:

#  cache:
#    cache-names: users
#    caffeine.spec: maximumSize=5000,expireAfterAccess=60s

logging:
  level:
    root: INFO
    com.woodpecker.woodpecker: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: INFO

server.servlet:
  encoding:
    charset: UTF-8 # Charset of HTTP requests and responses. Added to the "Content-Type" header if not set explicitly
    enabled: true # Enable http encoding support
server:
  port: 9090
