global:
  scrape_interval: 5s
  evaluation_interval: 5s
scrape_configs:
  - job_name: 'backend'
    metrics_path: '/actuator/prometheus'
    static_configs:
    - targets: [ 'backend:9090' ]
  - job_name: 'store'
    metrics_path: '/actuator/prometheus'
    static_configs:
    - targets: [ 'store:9091' ]